---
- name: Install Required Package
  become: yes
  yum:
    name:
      - krb5-libs
      - krb5-workstation
    state: present

- name: Create krb5.conf
  template:
    src: "krb5.conf.j2"
    dest: "/etc/krb5.conf"
